name = "jaspergabriel-dev"
main = "worker/index.ts"
compatibility_date = "2025-01-01"

[assets]
directory = "./dist"
run_worker_first = ["/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "toasts"
database_id = "711c7434-7309-49c4-ab48-5e3b1e08d954"
